<?php

namespace AppBundle\Repository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{



    public function  getLastTweets($maxResults = 10)
    {

        return $this->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.createdAt','DESC')
            ->setMaxResults($maxResults)
            ->getQuery()
            ->getResult();
    }

    public function  getTweet($id)
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.id = :id')
            ->setParameter(':id',$id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
